{% set name = "prefect-ray" %}
{% set version = "0.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9375efeadf0cdc8b790507aa3396a78173fe392195d8fd235c3852a2c808deb3

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  noarch: python

requirements:
  host:
    - pip
    - python  >=3.8
  run:
    - prefect >=2.8.2
    - ray-core
    - python >=3.8

test:
  imports:
    - prefect_ray
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/PrefectHQ/prefect-ray
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Prefect integrations with the Ray execution framework.
  doc_url: https://prefecthq.github.io/prefect-ray/
  dev_url: https://github.com/PrefectHQ/prefect-ray

extra:
  recipe-maintainers:
    - madkinsz
    - desertaxle
    - ahuang11
